course/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.Index.as_view(), name='index'),
    url(r'^topic/$', views.CreateTopic.as_view(), name = 'register_topic'),
    url(r'^topic/list/$', views.ListTopic.as_view(), name = 'topic_list'),
    url(r'topic/edit/(?P<pk>[0-9]+)/$', views.UpdateTopic.as_view(), name = 'update_topic'),
    url(r'topic/details/(?P<pk>[0-9]+)/$', views.TopicDetails.as_view(), name = 'topic_details'),
    url(r'^course/$', views.CreateCourse.as_view(), name = 'create_course'),
    url(r'^course/list/$', views.ListCourse.as_view(), name = 'course_list'),
    url(r'^course/edit/(?P<pk>[0-9]+)/$', views.UpdateCourse.as_view(), name = 'update_course'),
    url(r'^class/$', views.CreateClass.as_view(), name = 'create_class'),
    url(r'^class/list/$', views.ListClass.as_view(), name = 'class_list'),
    url(r'^class/edit/(?P<pk>[0-9]+)/$', views.UpdateClass.as_view(), name = 'update_class'),
]

std/urls.py
from django.conf.urls import url
from . import views
from .views import Index, RegisterView, RegisterStudentTableView, InterestedStudentRegisterView, InterestedStudentTableView


urlpatterns = [
    url(r'^$', Index.as_view(), name='index'),
    url(r'^interested_student/$', InterestedStudentRegisterView.as_view(), name = 'interest_student_form' ),
    url(r'^interested_student_table/$', InterestedStudentTableView.as_view(), name='interested_student_table'),
    url(r'^register/$', RegisterView.as_view(), name ='register_form'),
    url(r'^student_table/$', RegisterStudentTableView.as_view(), name ='register_table'),
    url(r'^student/details/(?P<pk>[0-9]+)/$', views.RegisterStudentDetailsView.as_view(), name ='student_detail_view'),
    url(r'^student/edit/(?P<pk>[0-9]+)/$', views.UpdateRegisterStudent.as_view(), name ='student_update_view'),
]

student/urls.py
from django.conf.urls import url, include
from django.core.urlresolvers import reverse
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from std.views import Index


urlpatterns = [
     url(r'^$', Index.as_view(), name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^itsd/', include ('std.urls', namespace='std')),
    url(r'^itsd/', include('course.urls', namespace='course')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

course/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.core.urlresolvers import reverse

#topic model
class Topic(models.Model):
    topic_name = models.CharField(max_length=20)
    details = models.TextField()

    def get_absolute_url(self):
        return reverse('course:topic_list')

    def __str__(self):
        return self.topic_name



#course model
class Course(models.Model):
    topic_name = models.ForeignKey(Topic)
    course_name = models.CharField(max_length=50)
    category_name = models.CharField(max_length = 20)
    course_amount = models.CharField(max_length = 20)
    teacher_name = models.CharField(max_length=20)
    contact_number = models.CharField(max_length=20)

    def get_absolute_url(self):
        return reverse('course:course_list')

    def __str__(self):
        return self.course_name



#class model
class Class(models.Model):
    topic_name = models.ForeignKey(Topic)
    course_name = models.ForeignKey(Course)
    start_date = models.DateField()
    end_date = models.DateField()

    def get_absolute_url(self):
        return reverse('course:class_list')

course/forms.py
from django import forms
from .models import Topic, Course, Class


#topic form
class TopicForm(forms.ModelForm):
    topic_name = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class': 'form-control'}))
    details = forms.CharField(widget=forms.Textarea(attrs={'class' : 'form-control'}))

    class Meta:
        model = Topic
        fields = ['topic_name','details']


#course form
class CourseForm(forms.ModelForm):

    CHOICES = (('', 'select course'), ('Python', 'Python'), ('Java Script', 'Java Script'),
               ('Web Design', 'Web Design'), ('Php', 'Php'),
               ('Networking', 'Networking'), ('Graphics', 'Graphics'),
               ('Wordpress', 'Wordpress'), ('SEO', 'SEO'),
               ('IT Manager', 'IT Manager'), )

    CHOICESS = (('', 'select category'), ('Basic', 'Basic'), ('Intermediate', 'Intermediate'),
               ('Advanced', 'Advanced'),)

    topic_name = forms.ModelChoiceField(queryset=Topic.objects.all(), widget=forms.Select(attrs={'class' : 'form-control'}))
    course_name = forms.ChoiceField(choices=CHOICES, widget=forms.Select(attrs={'class' : 'form-control'}))
    category_name = forms.ChoiceField(choices=CHOICESS, widget=forms.Select(attrs={'class': 'form-control'}))
    # course_amount = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class' : 'form-control'}))
    teacher_name = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class' : 'form-control'}))
    contact_number = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class' : 'form-control'}))

    class Meta:
        model = Course
        fields = ['topic_name', 'course_name', 'category_name', 'teacher_name', 'contact_number']



# class form
class ClassForm(forms.ModelForm):
    CHOICES = (('', 'select your course'), ('Basic', 'Basic'), ('Intermediate', 'Intermediate'),
               ('Advanced', 'Advanced'),)

    topic_name = forms.ModelChoiceField(queryset = Topic.objects.all(), widget=forms.Select(attrs = {'class': 'form-control'}))
    course_name = forms.ModelChoiceField(queryset = Course.objects.all(), widget=forms.Select(attrs = {'class': 'form-control'}))
    start_date = forms.DateField(widget=forms.widgets.DateInput(format="%d %B, %Y",attrs = {'class': 'form-control','type' : 'date'}))
    end_date = forms.DateField(widget=forms.widgets.DateInput(format="%d %B, %Y", attrs = {'class': 'form-control','type' : 'date'}))

    class Meta:
        model = Class
        fields = ['topic_name', 'course_name', 'start_date', 'end_date']

course/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views.generic.edit import CreateView, UpdateView, View
from django.views import generic
from .models import Topic, Course, Class
from django.utils import timezone
from .forms import TopicForm, CourseForm, ClassForm
from django.contrib.messages.views import SuccessMessageMixin


#index view
class Index(View):
    template_name = "dashboard/dashboard.html"
    def get(self, request):
        return render(request, self.template_name)


#create topic
class CreateTopic(CreateView):
    template_name = 'forms/topic_form.html'
    def get(self, request, pk=None):
        form = TopicForm()
        context = timezone.now()
        return render(request, self.template_name, {
            'form' : form,
            'now' : context
        })

    def post(self, request):
        form = TopicForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/itsd/topic/list/')
        context = timezone.now()
        return render(request, self.template_name, {
            'form' : form,
            'now' : context
        })


#List Topic
class ListTopic(generic.ListView):
    template_name = 'tables/topic_table.html'
    def get_queryset(self):
        return Topic.objects.all()

    def get_context_data(self, **kwargs):
        context = super(ListTopic, self).get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context


#update topic
class UpdateTopic(SuccessMessageMixin, UpdateView):
    model = Topic
    template_name = 'forms/topic_edit.html'
    form_class = TopicForm
    success_message = "Topic updated successfully!!!"

    def get_context_data(self, **kwargs):
        context = super(UpdateTopic, self).get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context


#topic details
class TopicDetails(generic.DetailView):
    template_name = 'tables/topic_details.html'
    model = Topic

    def get_context_data(self, **kwargs):
        context = super(TopicDetails, self).get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context


#create course
class CreateCourse(CreateView):
    template_name = 'forms/course_form.html'

    def get(self, request):
        form = CourseForm
        context = timezone.now()
        return render(request, self.template_name, {
            'form' : form,
            'now' : context
        })

    def post(self, request):
        form = CourseForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/itsd/course/list/')
        return render(request, self.template_name)


#course list view
class ListCourse(generic.ListView):
    template_name = "tables/course_table.html"
    def get_queryset(self):
        return Course.objects.all()

    def get_context_data(self, **kwargs):
        context = super(ListCourse, self).get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context


#course update view
class UpdateCourse(SuccessMessageMixin, UpdateView):
    model = Course
    template_name = 'forms/course_edit.html'
    form_class = CourseForm
    success_message = "Course updated successfully!!!"

    def get_context_data(self, **kwargs):
        context = super(UpdateCourse, self).get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context



#create class
class CreateClass(CreateView):
    template_name = 'forms/class_form.html'

    def get(self, request):
        form = ClassForm
        context = timezone.now()
        return render(request, self.template_name, {
            'form' : form,
            'now' : context
        })

    def post(self, request):
        form = ClassForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/itsd/class/list/')
        return render(request, self.template_name, {
            'form' : form
        })


#update class
class UpdateClass(SuccessMessageMixin, UpdateView):
    model = Class
    template_name = 'forms/class_form.html'
    form_class = ClassForm
    success_message = "Class updated successfully"

    def get_context_data(self, **kwargs):
        context = super(UpdateClass, self).get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context


#Class List
class ListClass(generic.ListView):
    template_name = 'tables/class_table.html'
    def get_queryset(self):
        return Class.objects.all()

    def get_context_data(self, **kwargs):
        context = super(ListClass, self).get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context

templates/tables/class_table.html
{% extends 'app.html' %}
{% block content %}
        <!-- Main content -->
	<main class="main">
	<div class="container-fluid">
    	<div class="animated fadeIn">
			<div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <i class="fa fa-align-justify"></i> Class Table

                            <b class="pull-right">Date: {{ now|date }}</b>
                        </div>
                            {% if messages %}
                            <ul class="messages">
                                <div class="alert alert-success">
                                {% for message in messages %}
                                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                                {% endfor %}
                                </div>
                            </ul>
                            {% endif %}
                        <div class="card-body">
                            <table class="table table-bordered table-striped table-sm">
                                <thead class="text-center">
                                    <tr>
                                        <th class="text-center">Topic Name</th>
                                        <th class="text-center">Course Name</th>
                                        <th class="text-center">Start Date</th>
                                        <th class="text-center">End Date</th>
                                        <th class="text-center">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for class in object_list %}
                                    <tr>
                                        <td class="text-center">{{ class.topic_name }}</td>
                                        <td class="text-center">{{ class.course_name }}</td>
                                        <td class="text-center">{{ class.start_date }}</td>
                                        <td class="text-center">{{ class.end_date }}</td>
                                        <td class="text-center">
                                            <a href="{% url 'course:update_class' class.id %}"><button type="button" class="btn btn-info">Edit</button></a>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <!--/.col-->
            </div>
            <!--/.row-->
        </div>

    </div>
    <!-- /.conainer-fluid -->
</main>
{% endblock %}

templates/tables/course_table.html
{% extends 'app.html' %}
{% block content %}			
        <!-- Main content -->
	<main class="main">
	<div class="container-fluid">
    	<div class="animated fadeIn">
			<div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <i class="fa fa-align-justify"></i> Course Table

                            <b class="pull-right">Date: {{ now|date }}</b>
                        </div>
                            {% if messages %}
                            <ul class="messages">
                                <div class="alert alert-success">
                                {% for message in messages %}
                                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                                {% endfor %}
                                </div>
                            </ul>
                            {% endif %}
                        <div class="card-body">
                            <table class="table table-bordered table-striped table-sm">
                                <thead>
                                    <tr>
                                        <th>Topic</th>
                                        <th>Course</th>
                                        <th>Category</th>
                                        <th>Course Amount</th>
                                        <th>Teacher's Name</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for course in object_list %}
                                    <tr>
                                        <td>{{ course.topic_name }}</td>
                                        <td>{{ course.course_name }}</td>
                                        <td>{{ course.category_name }}</td>
                                        <td>{{ course.course_amount }}</td>
                                        <td>{{ course.teacher_name }}</td>
                                        <td>
                                            <a href="{% url 'course:update_course' pk=course.id %}"><span class="btn btn-info">Edit</span></a>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <!--/.col-->
            </div>
            <!--/.row-->
        </div>

    </div>
    <!-- /.conainer-fluid -->
</main>
{% endblock %}

templates/tables/interested_students_table.html
{% extends 'app.html' %}
{% block content %}			
        <!-- Main content -->
	<main class="main">
	<div class="container-fluid">
    	<div class="animated fadeIn">
			<div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <i class="fa fa-align-justify"></i> Interested Students Table

                            <b class="pull-right">Date: {{ now|date }}</b>
                        </div>
                        <div class="card-body">
                            <table class="table table-bordered table-striped table-sm text-center">
                                <thead>
                                    <h5><strong>Student Information</strong></h5>
                                    <tr class="text-center">
                                        <th class="text-center">Name</th>
                                        <th class="text-center">Course Name</th>
                                        <th class="text-center">Institute</th>
                                        <th class="text-center">Ocupation</th>
                                        <th class="text-center">Address</th>
                                        <th class="text-center">phone Number</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for students in student %}
                                    <tr>
                                        <td>{{students.name}}</td>
                                        <td>{{students.course_name}}</td>
                                        <td>{{students.institute_name}}</td>
                                        <td>{{students.ocupation}}</td>
                                        <td>{{students.address}}</td>
                                        <td>{{students.phone_no}}</td>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <!--/.col-->
            </div>
            <!--/.row-->
        </div>

    </div>
    <!-- /.conainer-fluid -->
</main>
 {% endblock %}

templates/tables/register_student_table.html
{% extends 'app.html' %}
{% block content %}		
        <!-- Main content -->
	<main class="main">
	<div class="container-fluid">
    	<div class="animated fadeIn">
			<div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <i class="fa fa-align-justify"></i> ITSD Students Table

                            <b class="pull-right">Date: {{ now|date }}</b>
                        </div>
                        <div class="card-body">
                            <table class="table table-bordered table-striped table-sm">

                            {% if messages %}
                            <ul class="messages">
                                <div class="alert alert-success">
                                {% for message in messages %}
                                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                                {% endfor %}
                                </div>
                            </ul>
                            {% endif %}
                                <thead>
                                    <h5><strong>Student Information</strong></h5>
                                    <tr>
                                        <th>Name</th>
                                        <th>Email</th>
                                        <th>Course Name</th>
                                        <th>Phone No</th>
                                        <th class="text-center">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for student in students %}
                                        <tr>
                                            <td>{{student.name}}</td>
                                            <td>{{student.email}}</td>
                                            <td>{{student.course_name}}</td>
                                            <td>{{student.phone_no}}</td>
                                            <td>
                                            <a href="{% url 'std:student_detail_view' student.id %}" class="pull-left"><button type="button" class="btn btn-info">View</button></a>
                                           
                                            <a href="{% url 'std:student_update_view'  pk=student.id%}" class="pull-right"><button type="button" class="btn btn-success">Edit</button></a>

                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <!--/.col-->
            </div>
            <!--/.row-->
        </div>

    </div>
    <!-- /.conainer-fluid -->
</main>
{% endblock %}

templates/tables/student_details_table.html
{% extends 'app.html' %}
{% block content %}
        <!-- Main content -->
	<main class="main">
	<div class="container-fluid">
    	<div class="animated fadeIn">
			<div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <i class="fa fa-align-justify"></i> ITSD Students Table
                            <b class="pull-right">Date: {{ now|date }}</b>
                        </div>
                        <div class="card-body">
                            <table class="table table-bordered table-striped table-sm">

                                <thead>
                                    <h5><strong>Student Information</strong></h5>
                                    <tr>
                                        <th>Name</th>
                                        <th>Father's Name</th>
                                        <th>Mother's Name</th>
                                        <th>Email</th>
                                        <th>Course Name</th>
                                    </tr>
                                </thead>
                                <tbody>
                                        <tr>
                                            <td>{{ object.father_name }}</td>
                                            <td>{{ object.mother_name }}</td>
                                            <td>{{ object.name }}</td>
                                            <td>{{ object.email }}</td>
                                            <td>{{ object.course_name }}</td>

                                        </tr>
                                </tbody>
                            </table>
                            <table class="table table-bordered table-striped table-sm">
                                <thead>
                                    <tr>
                                        <th>Current Address</th>
                                        <th>Phone No</th>
                                        <th>Ocupation</th>
                                        <th>Date of birth</th>
                                        <th>Machine</th>
                                    </tr>
                                </thead>
                                <tbody>
                                        <tr>
                                            <td>{{ object.current_address }}</td>
                                            <td>{{ object.phone_no }}</td>
                                            <td>{{ object.ocupation }}</td>
                                            <td>{{ object.date_of_birth }}</td>
                                            <td>{{ object.machine }}</td>

                                        </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <!--/.col-->
            </div>
            <!--/.row-->
        </div>

    </div>
    <!-- /.conainer-fluid -->
</main>
{% endblock %}

templates/tables/topic_details.html
{% extends 'app.html' %}
{% block content %}
        <!-- Main content -->
	<main class="main">
	<div class="container-fluid">
    	<div class="animated fadeIn">
			<div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <i class="fa fa-align-justify"></i> Class Table

                            <b class="pull-right">Date: {{ now|date }}</b>
                        </div>
                        <div class="card-body">
                            <h2 class="text-center"><span class="text-bold">Topic Name : </span>{{object.topic_name }}</h2>
                            <br>
                                <h4 class="text-center"> Description </h4>
                            <br>
                            <p class="text-center">{{ object.details }}</p>
                        </div>
                    </div>
                </div>
                <!--/.col-->
            </div>
            <!--/.row-->
        </div>

    </div>
    <!-- /.conainer-fluid -->
</main>
{% endblock %}

templates/tables/topic_table.html
{% extends 'app.html' %}
{% block content %}
        <!-- Main content -->
	<main class="main">
	<div class="container-fluid">
    	<div class="animated fadeIn">
			<div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <i class="fa fa-align-justify"></i> Topic Table

                             <b class="pull-right">Date: {{ now|date }}</b>
                        </div>
                            {% if messages %}
                            <ul class="messages">
                                <div class="alert alert-success">
                                {% for message in messages %}
                                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                                {% endfor %}
                                </div>
                            </ul>
                            {% endif %}
                        <div class="card-body">
                            <table class="table table-bordered table-striped table-sm">
                                <thead>
                                    <tr>
                                        <th class="text-center">Course Name</th>
                                        <th class="text-center">Action</th>
                                        <th class="text-center">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for topic in object_list %}
                                    <tr>
                                        <td class="text-center">{{ topic.topic_name}}</td>
                                        <td class="text-center">
                                            <a href="{% url 'course:topic_details' pk=topic.id %}"><span class="btn btn-info">details</span></a>
                                        </td>
                                        <td class="text-center">
                                            <a href="{% url 'course:update_topic' pk=topic.pk %}"><span class="btn btn-success">Edit</span></a>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <!--/.col-->
            </div>
            <!--/.row-->
        </div>

    </div>
    <!-- /.conainer-fluid -->
</main>
{% endblock %}