course/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.Index.as_view(), name='index'),
    url(r'^topic/$', views.CreateTopic.as_view(), name = 'register_topic'),
    url(r'^topic/list/$', views.ListTopic.as_view(), name = 'topic_list'),
    url(r'topic/edit/(?P<pk>[0-9]+)/$', views.UpdateTopic.as_view(), name = 'update_topic'),
    url(r'topic/details/(?P<pk>[0-9]+)/$', views.TopicDetails.as_view(), name = 'topic_details'),
    url(r'^course/$', views.CreateCourse.as_view(), name = 'create_course'),
    url(r'^course/list/$', views.ListCourse.as_view(), name = 'course_list'),
    url(r'^course/edit/(?P<pk>[0-9]+)/$', views.UpdateCourse.as_view(), name = 'update_course'),
    url(r'^class/$', views.CreateClass.as_view(), name = 'create_class'),
    url(r'^class/list/$', views.ListClass.as_view(), name = 'class_list'),
    url(r'^class/edit/(?P<pk>[0-9]+)/$', views.UpdateClass.as_view(), name = 'update_class'),
]

std/urls.py
from django.conf.urls import url
from . import views
from .views import Index, RegisterView, RegisterStudentTableView, InterestedStudentRegisterView, InterestedStudentTableView


urlpatterns = [
    url(r'^$', Index.as_view(), name='index'),
    url(r'^interested_student/$', InterestedStudentRegisterView.as_view(), name = 'interest_student_form' ),
    url(r'^interested_student_table/$', InterestedStudentTableView.as_view(), name='interested_student_table'),
    url(r'^register/$', RegisterView.as_view(), name ='register_form'),
    url(r'^student_table/$', RegisterStudentTableView.as_view(), name ='register_table'),
    url(r'^student/details/(?P<pk>[0-9]+)/$', views.RegisterStudentDetailsView.as_view(), name ='student_detail_view'),
    url(r'^student/edit/(?P<pk>[0-9]+)/$', views.UpdateRegisterStudent.as_view(), name ='student_update_view'),
]

student/urls.py
from django.conf.urls import url, include
from django.core.urlresolvers import reverse
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from std.views import Index


urlpatterns = [
     url(r'^$', Index.as_view(), name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^itsd/', include ('std.urls', namespace='std')),
    url(r'^itsd/', include('course.urls', namespace='course')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/layouts/sidebars/sidebar.html
<div class="sidebar">
    <nav class="sidebar-nav">
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href=""><i class="icon-speedometer"></i> ITSD </a>
            </li>

            <li class="nav-title">
                MENU
            </li>
             <li class="nav-item nav-dropdown">
                <a class="nav-link nav-dropdown-toggle" href="#"><i class="icon-puzzle"></i> Forms</a>
                <ul class="nav-dropdown-items">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'std:interest_student_form' %}"><i class="icon-puzzle"></i> Interested Students Regitration</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'std:register_form' %}"><i class="icon-puzzle"></i> ITSD Students Registration</a>
                    </li>
                </ul>
            </li>
             <li class="nav-item nav-dropdown">
                <a class="nav-link nav-dropdown-toggle" href="#"><i class="icon-puzzle"></i> Tables</a>
                <ul class="nav-dropdown-items">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'std:interested_student_table' %}"><i class="icon-puzzle"></i> Interested Students Table</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'std:register_table' %}"><i class="icon-puzzle"></i> ITSD Students Table</a>
                    </li>
                </ul>
            </li>
             <li class="nav-item nav-dropdown">
                <a class="nav-link nav-dropdown-toggle" href="#"><i class="icon-puzzle"></i> Topic & Course</a>
                <ul class="nav-dropdown-items">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'course:register_topic' %}"><i class="icon-puzzle"></i> Create Topic</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'course:create_course' %}"><i class="icon-puzzle"></i> Create Course </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'course:create_class' %}"><i class="icon-puzzle"></i> Create Class</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'course:topic_list'  %}"><i class="icon-puzzle"></i>Topic Table</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'course:course_list'  %}"><i class="icon-puzzle"></i>Course Table</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'course:class_list'  %}"><i class="icon-puzzle"></i>Class Table</a>
                    </li>
                </ul>
            </li>
        </ul>
    </nav>
</div>